---
- name: install docker
  hosts: jenkins
  tasks:
    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - docker
    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes
